### ISSUE TITLE
Mac OS X Build

### ISSUE THREAD

**Issue by jphastings** [carsonmcdonald/HTTP-Live-Video-Stream-Segmenter-and-Distributor#1]
preface: You've mentioned you haven't tested on Mac OS X, so this is more of a request for help than an issue!

I'm attempting to build the live_segmenter on Mac OS X (specifically Snow Leopard) and I'm running into problems, maybe someone with more technical knowledge can help!

This is my current flow:
1. git clone git://github.com/carsonmcdonald/HTTP-Live-Video-Stream-Segmenter-and-Distributor.git
2. `make` (in root directory) 
   plenty of errors ( http://pastebin.com/fec11bae ) caused by lack of libraries
3. Use macports to install ffmpeg-devel, libconfig (a hack is required to install libsdl - http://trac.macports.org/attachment/ticket/20235/libsdl.patch)
4. Alter the makefile to make sure gcc can find the macports libraries:
   [line 2] gcc -Wall -I/opt/local/include -L/opt/local/lib -g live_segmenter.c ... etc (same as before)
   build is sucessful
5. ./live_segmenter
   dyld: Library not loaded: libopennet.dylib
     Referenced from: /opt/local/lib/libconfig.0.2.3.dylib
     Reason: image not found
   Trace/BPT trap
6. ls -l /opt/local/lib/libopennet.dylib 
   lrwxr-xr-x  1 root  admin  22 30 Aug 13:39 /opt/local/lib/libopennet.dylib -> libopennet.0.9.9.dylib
   the library exists! All I can assume is that the non-standard location of the dynamic libraries (in /opt/local rather than /usr/) means the file, though it exists, isn't being found.

Any help would be greatly appreciated!

**Comment by mdonahoe** [comment]
With your modifications to the makefile, it worked perfectly on my mac. Thanks! Maybe try the new version of ffmpeg from macports?

**Comment by jphastings** [comment]
Sweet - will give it a try! I'm using homebrew (its here on github) instead of macports, but I'll give it another shot, should work!

**Comment by tvdeyen** [comment]
I can confirm that compiling on Mac OS X 10.6.4 is successful after your changes.

**Comment by tvdeyen** [comment]
I wrote a wiki article. This ticket may be closed.

**Comment by jphastings** [comment]
Cool, thanks!
